services:
  app:
    build:
      context: .
    image: nextjs-prod
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: whoflopped_user
      POSTGRES_PASSWORD: 1010
      POSTGRES_DB: whoflopped_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U whoflopped_user -d whoflopped_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
